model: "openai/gpt-3.5-turbo-0301"
type: CHAT
conv_template: llama-2

model_loader: HF
torch_dtype: null
quant_file: null
tokenizer_name: meta-llama/Llama-2-13b-chat-hf
trust_remote_code: true
use_auth_token: true