model: "hf/vita-group/vicuna-13b-v1.3_magnitude_semistruct@0.5_2to4"
type: CHAT
conv_template: "vicuna_v1.1"

model_loader: HF
torch_dtype: BFLOAT16
quant_file: null
tokenizer_name: vicuna-13b-v1.3
trust_remote_code: true
use_auth_token: true